package com.nicos.pitchkit.tuner.harmony.chordformer

import java.io.File
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.abs
import kotlin.math.sqrt
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Independent librosa golden data for ChordFormer's `extractors/cqt.py::CQTV2`:
 * hybrid CQT magnitudes, `amplitude_to_db(ref=np.max)` over all 288 bins, then the
 * 18..270 model crop. Generated by
 * `tools/accuracy_audit/export_chordformer.py --stage cqt` with the same librosa 0.9.2
 * the upstream checkpoints were trained against.
 *
 * The Android frontend approximates librosa's resampler with a fixed FIR half-band and
 * its pseudo-CQT with a sparse magnitude basis, so this asserts agreement, not equality:
 * the dB floor and ceiling have to be reproduced exactly, and the shape of every frame
 * has to match.
 */
class ChordFormerCqtParityTest {
    @Test
    fun matchesTheLibrosaCqtV2Reference() {
        val provenance = JSONObject(
            resource("chordformer-cqt-provenance.json").toString(Charsets.UTF_8)
        )
        assertEquals(1, provenance.getInt("schema_version"))
        assertEquals(ChordFormerContract.SAMPLE_RATE, provenance.getInt("sample_rate"))
        assertEquals(ChordFormerContract.HOP_LENGTH, provenance.getInt("hop_length"))
        assertEquals(ChordFormerContract.ORIGINAL_HYBRID_BINS, provenance.getInt("original_bins"))
        assertEquals(ChordFormerContract.INPUT_BINS, provenance.getInt("input_bins"))

        val audio = floats(resource("chordformer-cqt-audio.f32"))
        val expected = floats(resource("chordformer-cqt-expected.f32"))
        val referenceFrames = provenance.getInt("frames")
        assertEquals(referenceFrames * ChordFormerContract.INPUT_BINS, expected.size)

        val frontend = ChordFormerCqtFrontend(
            lowPlanBytes = asset(ChordFormerContract.LOW_CQT_PLAN_FILE),
            highPlanBytes = asset(ChordFormerContract.HIGH_CQT_PLAN_FILE),
        )
        val actual = frontend.transform(audio)
        assertEquals("Frame count", referenceFrames, actual.frameCount)

        // ref=np.max means the loudest bin of the whole spectrogram is 0 dB and the floor
        // is exactly -80 dB. Both have to survive the port or the normalisation is wrong.
        var peak = Float.NEGATIVE_INFINITY
        var lowest = Float.POSITIVE_INFINITY
        for (value in actual.values) {
            if (value > peak) peak = value
            if (value < lowest) lowest = value
        }
        assertTrue("dB ceiling $peak", peak <= 0.0001f)
        assertTrue("dB ceiling $peak", peak > -12f)
        assertTrue("dB floor $lowest", lowest >= -80.0001f)

        val agreement = compare(actual.values, expected, actual.frameCount)
        println("chordformer cqt: frames=${actual.frameCount} $agreement")
        assertTrue("Mean frame cosine: ${agreement.cosine}", agreement.cosine >= .99)
        assertTrue("Mean normalized dB error: ${agreement.meanError}", agreement.meanError <= .05)
        assertTrue("Max dB error: ${agreement.maxDecibelError}", agreement.maxDecibelError <= 12.0)
        assertTrue(
            "Dominant bin agreement: ${agreement.dominantAgreement}",
            agreement.dominantAgreement >= .95,
        )

        // Vacuity guard: a comparison that passes for the wrong spectrogram too would
        // prove nothing about the port, so the same stimulus played backwards must fail
        // these thresholds by a wide margin.
        val reversed = frontend.transform(audio.reversedArray())
        assertEquals(actual.frameCount, reversed.frameCount)
        val control = compare(reversed.values, expected, reversed.frameCount)
        println("chordformer cqt (time-reversed control): $control")
        assertTrue("Control cosine: ${control.cosine}", control.cosine < .9)
        assertTrue(
            "Control dominant agreement: ${control.dominantAgreement}",
            control.dominantAgreement < .5,
        )
    }

    private data class Agreement(
        val cosine: Double,
        val meanError: Double,
        val maxDecibelError: Double,
        val dominantAgreement: Double,
    ) {
        override fun toString() = "mean cosine=$cosine mean |delta|=$meanError " +
            "max |delta| dB=$maxDecibelError dominant-bin agreement=$dominantAgreement"
    }

    private fun compare(actual: FloatArray, expected: FloatArray, frames: Int): Agreement {
        var cosineSum = 0.0
        var absoluteError = 0.0
        var maxDecibelError = 0.0
        var dominantMatches = 0
        var measuredFrames = 0
        for (frame in 0 until frames) {
            val start = frame * ChordFormerContract.INPUT_BINS
            var dot = 0.0
            var aa = 0.0
            var bb = 0.0
            var actualPeakBin = 0
            var expectedPeakBin = 0
            for (bin in 0 until ChordFormerContract.INPUT_BINS) {
                // Compare where the energy is, not how deep the shared silence floor is:
                // 80 dB below the loudest bin of the song carries no chord information and
                // its logarithm magnifies resampler noise without bound.
                val a = (actual[start + bin] + 80.0) / 80.0
                val b = (expected[start + bin] + 80.0) / 80.0
                dot += a * b
                aa += a * a
                bb += b * b
                absoluteError += abs(a - b)
                maxDecibelError = maxOf(
                    maxDecibelError,
                    abs(actual[start + bin] - expected[start + bin]).toDouble(),
                )
                if (actual[start + bin] > actual[start + actualPeakBin]) actualPeakBin = bin
                if (expected[start + bin] > expected[start + expectedPeakBin]) expectedPeakBin = bin
            }
            if (aa > 1e-9 && bb > 1e-9) {
                cosineSum += dot / sqrt(aa * bb)
                if (abs(expectedPeakBin - actualPeakBin) <= 1) dominantMatches++
                measuredFrames++
            }
        }
        return Agreement(
            cosine = cosineSum / measuredFrames,
            meanError = absoluteError / (measuredFrames * ChordFormerContract.INPUT_BINS),
            maxDecibelError = maxDecibelError,
            dominantAgreement = dominantMatches.toDouble() / measuredFrames,
        )
    }

    private fun resource(name: String) =
        requireNotNull(javaClass.getResourceAsStream("/$name")) { name }.use { it.readBytes() }

    private fun floats(bytes: ByteArray): FloatArray {
        val buffer = ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN).asFloatBuffer()
        return FloatArray(buffer.remaining()).also { buffer.get(it) }
    }

    private fun asset(name: String): ByteArray = ChordFormerTestAssets.locate(name).readBytes()
}

internal object ChordFormerTestAssets {
    fun locate(name: String): File {
        var directory: File? = File(System.getProperty("user.dir") ?: ".").absoluteFile
        while (directory != null) {
            val candidate = File(
                directory,
                "src/main/assets/${ChordFormerContract.ASSET_DIRECTORY}/$name",
            )
            if (candidate.isFile) return candidate
            val nested = File(
                directory,
                "PitchKit/PitchKit/src/main/assets/${ChordFormerContract.ASSET_DIRECTORY}/$name",
            )
            if (nested.isFile) return nested
            directory = directory.parentFile
        }
        // ChordFormer has no licence, so its exported files are never committed; they
        // exist only where tools/accuracy_audit/export_chordformer.py has been run.
        throw org.junit.AssumptionViolatedException(
            "ChordFormer asset $name is not in this checkout (personal research files)"
        )
    }
}
