package com.nicos.pitchkit.tuner.harmony.animechord

import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.abs
import kotlin.math.max
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Golden data straight out of the reference `AudioFeatureExtractor`: the whole-clip
 * standardised `RecursiveCQT` of a 10 s excerpt, for one channel of a mono clip
 * duplicated to stereo. Generated by `tools/generate-animechord-cqt-plans.py`.
 *
 * Unlike the librosa-based front ends in this app, nothing here is approximated. The
 * kernels, the analysis window and the decimator taps are the reference's own buffers,
 * the STFT is the same `center=True` reflect-padded transform, and the decimation is the
 * same stride-2 correlation. So this asserts near-equality — 1e-4 relative, the tolerance
 * the port was asked for — not merely agreement, and the only slack is float32 rounding
 * and the order the two implementations accumulate 129-term dot products in.
 */
class AnimeChordCqtParityTest {
    @Test
    fun matchesTheReferenceRecursiveCqt() {
        org.junit.Assume.assumeTrue("Private reference audio is available only in the local audit workspace",
            javaClass.getResource("/animechord-cqt-audio.s16") != null)
        val provenance = JSONObject(
            resource("animechord-cqt-provenance.json").toString(Charsets.UTF_8)
        )
        assertEquals(1, provenance.getInt("schema_version"))
        assertEquals(AnimeChordContract.SAMPLE_RATE, provenance.getInt("sample_rate"))
        assertEquals(AnimeChordContract.HOP_LENGTH, provenance.getInt("hop_length"))
        assertEquals(AnimeChordContract.INPUT_BINS, provenance.getInt("bins"))

        val audio = pcm(resource("animechord-cqt-audio.s16"))
        assertEquals(provenance.getInt("samples"), audio.size)
        val expected = floats(resource("animechord-cqt-expected.f32"))
        val referenceFrames = provenance.getInt("frames")
        assertEquals(referenceFrames * AnimeChordContract.INPUT_BINS, expected.size)

        val frontend = AnimeChordCqtFrontend(
            AnimeChordTestAssets.read(AnimeChordContract.CQT_PLAN_FILE)
        )
        val actual = frontend.transform(audio)
        assertEquals("Frame count", referenceFrames, actual.frameCount)
        assertEquals("crop_length", provenance.getInt("crop_length"), actual.cropLength)

        // The reference standardises to zero mean and unit variance over the whole
        // (freq, time) block; if the port's normalisation drifted, this is where it shows.
        var sum = 0.0
        for (value in actual.values) sum += value.toDouble()
        assertEquals("mean", 0.0, sum / actual.values.size, 1e-4)

        var scale = 0.0
        for (value in expected) scale = max(scale, abs(value.toDouble()))
        var worstAbsolute = 0.0
        var worstRelative = 0.0
        var totalAbsolute = 0.0
        for (index in expected.indices) {
            val difference = abs(actual.values[index].toDouble() - expected[index].toDouble())
            totalAbsolute += difference
            worstAbsolute = max(worstAbsolute, difference)
            worstRelative = max(worstRelative, difference / scale)
        }
        val meanAbsolute = totalAbsolute / expected.size
        println(
            "animechord cqt: frames=${actual.frameCount} scale=$scale " +
                "max|delta|=$worstAbsolute mean|delta|=$meanAbsolute " +
                "max relative=$worstRelative"
        )
        assertTrue("Max relative error $worstRelative", worstRelative <= 1e-4)

        // Vacuity guard: the same stimulus played backwards must fail by a wide margin,
        // or the comparison above would pass for the wrong spectrogram too.
        val reversed = frontend.transform(audio.reversedArray())
        assertEquals(actual.frameCount, reversed.frameCount)
        var control = 0.0
        for (index in expected.indices) {
            control = max(
                control,
                abs(reversed.values[index].toDouble() - expected[index].toDouble()) / scale,
            )
        }
        println("animechord cqt (time-reversed control): max relative=$control")
        assertTrue("Control max relative $control", control > 0.1)
    }

    @Test
    fun aClipShorterThanTheCropWindowStillProducesFrames() {
        val frontend = AnimeChordCqtFrontend(
            AnimeChordTestAssets.read(AnimeChordContract.CQT_PLAN_FILE)
        )
        val audio = FloatArray(4096) { index ->
            (kotlin.math.sin(2.0 * Math.PI * 220.0 * index / 22050.0) * 0.5).toFloat()
        }
        val features = frontend.transform(audio)
        assertEquals(8, features.frameCount)
        assertEquals(5, features.cropLength)
        assertTrue(features.values.all { it.isFinite() })
        assertTrue(frontend.transform(FloatArray(0)).frameCount == 0)
    }

    private fun resource(name: String) =
        requireNotNull(javaClass.getResourceAsStream("/$name")) { name }.use { it.readBytes() }

    private fun floats(bytes: ByteArray): FloatArray {
        val buffer = ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN).asFloatBuffer()
        return FloatArray(buffer.remaining()).also { buffer.get(it) }
    }

    private fun pcm(bytes: ByteArray): FloatArray {
        val buffer = ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN).asShortBuffer()
        return FloatArray(buffer.remaining()) { buffer.get(it) / 32768.0f }
    }
}
